import { QuestionInfo } from "./types";

const DIMENSIONS = {
    "Soziale Kompetenzen": "Soziale Kompetenzen",
    "Psychische Konstitution": "Psychische Konstitution",
    "Berufliche Orientierung": "Berufliche Orientierung",
    Arbeitsverhalten: "Arbeitsverhalten",
} as const;

const CATEGORIES = {
    "Soziabilität (Soz)": "Soziabilität (Soz)",
    "Kontaktfähigkeit (Ko)": "Kontaktfähigkeit (Ko)",
    "Teamorientierung (TO)": "Teamorientierung (TO)",
    "Emotionale Stabilität (Est)": "Emotionale Stabilität (Est)",
    "Belastbarkeit (Bel)": "Belastbarkeit (Bel)",
    "Selbstbewusstsein (Sb)": "Selbstbewusstsein (Sb)",
    "Leistungsmotivation (LM)": "Leistungsmotivation (LM)",
    "Gestaltungsmotivation (GM)": "Gestaltungsmotivation (GM)",
    "Führungsmotivation (FM)": "Führungsmotivation (FM)",
    "Durchsetzungsstärke (Du)": "Durchsetzungsstärke (Du)",
    "Gewissenhaftigkeit (Ge)": "Gewissenhaftigkeit (Ge)",
    "Flexibilität (FI)": "Flexibilität (FI)",
    "Handlungsorientierung (HO)": "Handlungsorientierung (HO)",
    "Sensitivität (Sen)": "Sensitivität (Sen)",
};

const questions : QuestionInfo[] = [
    {
        questionId: 1,
        dimension: "Soziale Kompetenzen",
        category: "Soziabilität (Soz)",
        umkehr: false,
    },
    {
        questionId: 2,
        dimension: "Soziale Kompetenzen",
        category: "Kontaktfähigkeit (Ko)",
        umkehr: true,
    },
    {
        questionId: 3,
        dimension: "Soziale Kompetenzen",
        category: "Teamorientierung (TO)",
        umkehr: false,
    },
    {
        questionId: 4,
        dimension: "Psychische Konstitution",
        category: "Emotionale Stabilität (Est)",
        umkehr: true,
    },
    {
        questionId: 5,
        dimension: "Psychische Konstitution",
        category: "Belastbarkeit (Bel)",
        umkehr: false,
    },
    {
        questionId: 6,
        dimension: "Psychische Konstitution",
        category: "Selbstbewusstsein (Sb)",
        umkehr: true,
    },
    {
        questionId: 7,
        dimension: "Berufliche Orientierung",
        category: "Leistungsmotivation (LM)",
        umkehr: true,
    },
    {
        questionId: 8,
        dimension: "Berufliche Orientierung",
        category: "Gestaltungsmotivation (GM)",
        umkehr: true,
    },
    {
        questionId: 9,
        dimension: "Berufliche Orientierung",
        category: "Führungsmotivation (FM)",
        umkehr: false,
    },
    {
        questionId: 10,
        dimension: "Soziale Kompetenzen",
        category: "Durchsetzungsstärke (Du)",
        umkehr: true,
    },
    {
        questionId: 11,
        dimension: "Arbeitsverhalten",
        category: "Gewissenhaftigkeit (Ge)",
        umkehr: true,
    },
    {
        questionId: 12,
        dimension: "Arbeitsverhalten",
        category: "Flexibilität (FI)",
        umkehr: false,
    },
    {
        questionId: 13,
        dimension: "Arbeitsverhalten",
        category: "Handlungsorientierung (HO)",
        umkehr: false,
    },
    {
        questionId: 14,
        dimension: "Soziale Kompetenzen",
        category: "Sensitivität (Sen)",
        umkehr: true,
    },
    {
        questionId: 15,
        dimension: "Soziale Kompetenzen",
        category: "Soziabilität (Soz)",
        umkehr: true,
    },
    {
        questionId: 16,
        dimension: "Soziale Kompetenzen",
        category: "Kontaktfähigkeit (Ko)",
        umkehr: false,
    },
    {
        questionId: 17,
        dimension: "Soziale Kompetenzen",
        category: "Teamorientierung (TO)",
        umkehr: false,
    },
    {
        questionId: 18,
        dimension: "Psychische Konstitution",
        category: "Emotionale Stabilität (Est)",
        umkehr: true,
    },
    {
        questionId: 19,
        dimension: "Psychische Konstitution",
        category: "Belastbarkeit (Bel)",
        umkehr: true,
    },
    {
        questionId: 20,
        dimension: "Psychische Konstitution",
        category: "Selbstbewusstsein (Sb)",
        umkehr: false,
    },
    {
        questionId: 21,
        dimension: "",
        category: "Freizeitorientierung (Fo)",
        umkehr: true,
    },
    {
        questionId: 22,
        dimension: "Berufliche Orientierung",
        category: "Leistungsmotivation (LM)",
        umkehr: true,
    },
    {
        questionId: 23,
        dimension: "Berufliche Orientierung",
        category: "Gestaltungsmotivation (GM)",
        umkehr: false,
    },
    {
        questionId: 24,
        dimension: "Berufliche Orientierung",
        category: "Führungsmotivation (FM)",
        umkehr: false,
    },
    {
        questionId: 25,
        dimension: "Soziale Kompetenzen",
        category: "Durchsetzungsstärke (Du)",
        umkehr: true,
    },
    {
        questionId: 26,
        dimension: "Arbeitsverhalten",
        category: "Gewissenhaftigkeit (Ge)",
        umkehr: false,
    },
    {
        questionId: 27,
        dimension: "Arbeitsverhalten",
        category: "Flexibilität (FI)",
        umkehr: true,
    },
    {
        questionId: 28,
        dimension: "Arbeitsverhalten",
        category: "Handlungsorientierung (HO)",
        umkehr: true,
    },
    {
        questionId: 29,
        dimension: "Soziale Kompetenzen",
        category: "Sensitivität (Sen)",
        umkehr: false,
    },
    {
        questionId: 30,
        dimension: "Soziale Kompetenzen",
        category: "Soziabilität (Soz)",
        umkehr: true,
    },
    {
        questionId: 31,
        dimension: "Soziale Kompetenzen",
        category: "Kontaktfähigkeit (Ko)",
        umkehr: false,
    },
    {
        questionId: 32,
        dimension: "Soziale Kompetenzen",
        category: "Teamorientierung (TO)",
        umkehr: false,
    },
    {
        questionId: 33,
        dimension: "Psychische Konstitution",
        category: "Emotionale Stabilität (Est)",
        umkehr: true,
    },
    {
        questionId: 34,
        dimension: "Psychische Konstitution",
        category: "Belastbarkeit (Bel)",
        umkehr: false,
    },
    {
        questionId: 35,
        dimension: "Psychische Konstitution",
        category: "Selbstbewusstsein (Sb)",
        umkehr: true,
    },
    {
        questionId: 36,
        dimension: "",
        category: "Kontrollerleben (Ke)",
        umkehr: false,
    },
    {
        questionId: 37,
        dimension: "Berufliche Orientierung",
        category: "Leistungsmotivation (LM)",
        umkehr: true,
    },
    {
        questionId: 38,
        dimension: "Berufliche Orientierung",
        category: "Gestaltungsmotivation (GM)",
        umkehr: true,
    },
    {
        questionId: 39,
        dimension: "Berufliche Orientierung",
        category: "Führungsmotivation (FM)",
        umkehr: true,
    },
    {
        questionId: 40,
        dimension: "Soziale Kompetenzen",
        category: "Durchsetzungsstärke (Du)",
        umkehr: true,
    },
    {
        questionId: 41,
        dimension: "Arbeitsverhalten",
        category: "Gewissenhaftigkeit (Ge)",
        umkehr: true,
    },
    {
        questionId: 42,
        dimension: "Arbeitsverhalten",
        category: "Flexibilität (FI)",
        umkehr: true,
    },
    {
        questionId: 43,
        dimension: "Arbeitsverhalten",
        category: "Handlungsorientierung (HO)",
        umkehr: false,
    },
    {
        questionId: 44,
        dimension: "Soziale Kompetenzen",
        category: "Sensitivität (Sen)",
        umkehr: true,
    },
    {
        questionId: 45,
        dimension: "Soziale Kompetenzen",
        category: "Soziabilität (Soz)",
        umkehr: false,
    },
    {
        questionId: 46,
        dimension: "Soziale Kompetenzen",
        category: "Kontaktfähigkeit (Ko)",
        umkehr: false,
    },
    {
        questionId: 47,
        dimension: "Soziale Kompetenzen",
        category: "Teamorientierung (TO)",
        umkehr: false,
    },
    {
        questionId: 48,
        dimension: "Psychische Konstitution",
        category: "Emotionale Stabilität (Est)",
        umkehr: false,
    },
    {
        questionId: 49,
        dimension: "Psychische Konstitution",
        category: "Belastbarkeit (Bel)",
        umkehr: true,
    },
    {
        questionId: 50,
        dimension: "Psychische Konstitution",
        category: "Selbstbewusstsein (Sb)",
        umkehr: true,
    },
    {
        questionId: 51,
        dimension: "",
        category: "Kontrollerleben (Ke)",
        umkehr: false,
    },
    {
        questionId: 52,
        dimension: "",
        category: "Wettbewerbsorientierung (Wo)",
        umkehr: false,
    },
    {
        questionId: 53,
        dimension: "Berufliche Orientierung",
        category: "Leistungsmotivation (LM)",
        umkehr: true,
    },
    {
        questionId: 54,
        dimension: "Berufliche Orientierung",
        category: "Gestaltungsmotivation (GM)",
        umkehr: false,
    },
    {
        questionId: 55,
        dimension: "Berufliche Orientierung",
        category: "Führungsmotivation (FM)",
        umkehr: true,
    },
    {
        questionId: 56,
        dimension: "Soziale Kompetenzen",
        category: "Durchsetzungsstärke (Du)",
        umkehr: false,
    },
    {
        questionId: 57,
        dimension: "Arbeitsverhalten",
        category: "Gewissenhaftigkeit (Ge)",
        umkehr: true,
    },
    {
        questionId: 58,
        dimension: "Arbeitsverhalten",
        category: "Flexibilität (FI)",
        umkehr: false,
    },
    {
        questionId: 59,
        dimension: "Arbeitsverhalten",
        category: "Handlungsorientierung (HO)",
        umkehr: false,
    },
    {
        questionId: 60,
        dimension: "Soziale Kompetenzen",
        category: "Sensitivität (Sen)",
        umkehr: true,
    },
    {
        questionId: 61,
        dimension: "Soziale Kompetenzen",
        category: "Soziabilität (Soz)",
        umkehr: false,
    },
    {
        questionId: 62,
        dimension: "Soziale Kompetenzen",
        category: "Kontaktfähigkeit (Ko)",
        umkehr: false,
    },
    {
        questionId: 63,
        dimension: "Soziale Kompetenzen",
        category: "Teamorientierung (TO)",
        umkehr: true,
    },
    {
        questionId: 64,
        dimension: "Psychische Konstitution",
        category: "Emotionale Stabilität (Est)",
        umkehr: true,
    },
    {
        questionId: 65,
        dimension: "Psychische Konstitution",
        category: "Belastbarkeit (Bel)",
        umkehr: true,
    },
    {
        questionId: 66,
        dimension: "Psychische Konstitution",
        category: "Selbstbewusstsein (Sb)",
        umkehr: true,
    },
    {
        questionId: 67,
        dimension: "",
        category: "Kontrollerleben (Ke)",
        umkehr: true,
    },
    {
        questionId: 68,
        dimension: "",
        category: "Mobilität (M)",
        umkehr: false,
    },
    {
        questionId: 69,
        dimension: "Berufliche Orientierung",
        category: "Leistungsmotivation (LM)",
        umkehr: true,
    },
    {
        questionId: 70,
        dimension: "Berufliche Orientierung",
        category: "Gestaltungsmotivation (GM)",
        umkehr: true,
    },
    {
        questionId: 71,
        dimension: "Berufliche Orientierung",
        category: "Führungsmotivation (FM)",
        umkehr: true,
    },
    {
        questionId: 72,
        dimension: "Soziale Kompetenzen",
        category: "Durchsetzungsstärke (Du)",
        umkehr: true,
    },
    {
        questionId: 73,
        dimension: "Arbeitsverhalten",
        category: "Gewissenhaftigkeit (Ge)",
        umkehr: false,
    },
    {
        questionId: 74,
        dimension: "Arbeitsverhalten",
        category: "Flexibilität (FI)",
        umkehr: false,
    },
    {
        questionId: 75,
        dimension: "Arbeitsverhalten",
        category: "Handlungsorientierung (HO)",
        umkehr: false,
    },
    {
        questionId: 76,
        dimension: "Soziale Kompetenzen",
        category: "Sensitivität (Sen)",
        umkehr: true,
    },
    {
        questionId: 77,
        dimension: "Soziale Kompetenzen",
        category: "Soziabilität (Soz)",
        umkehr: true,
    },
    {
        questionId: 78,
        dimension: "Soziale Kompetenzen",
        category: "Kontaktfähigkeit (Ko)",
        umkehr: false,
    },
    {
        questionId: 79,
        dimension: "Soziale Kompetenzen",
        category: "Teamorientierung (TO)",
        umkehr: false,
    },
    {
        questionId: 80,
        dimension: "Psychische Konstitution",
        category: "Emotionale Stabilität (Est)",
        umkehr: false,
    },
    {
        questionId: 81,
        dimension: "Psychische Konstitution",
        category: "Belastbarkeit (Bel)",
        umkehr: true,
    },
    {
        questionId: 82,
        dimension: "Psychische Konstitution",
        category: "Selbstbewusstsein (Sb)",
        umkehr: false,
    },
    {
        questionId: 83,
        dimension: "",
        category: "Kontrollerleben (Ke)",
        umkehr: true,
    },
    {
        questionId: 84,
        dimension: "",
        category: "Mobilität (M)",
        umkehr: false,
    },
    {
        questionId: 85,
        dimension: "Berufliche Orientierung",
        category: "Leistungsmotivation (LM)",
        umkehr: true,
    },
    {
        questionId: 86,
        dimension: "Berufliche Orientierung",
        category: "Gestaltungsmotivation (GM)",
        umkehr: true,
    },
    {
        questionId: 87,
        dimension: "Berufliche Orientierung",
        category: "Führungsmotivation (FM)",
        umkehr: true,
    },
    {
        questionId: 88,
        dimension: "Soziale Kompetenzen",
        category: "Durchsetzungsstärke (Du)",
        umkehr: true,
    },
    {
        questionId: 89,
        dimension: "Arbeitsverhalten",
        category: "Gewissenhaftigkeit (Ge)",
        umkehr: false,
    },
    {
        questionId: 90,
        dimension: "Arbeitsverhalten",
        category: "Flexibilität (FI)",
        umkehr: false,
    },
    {
        questionId: 91,
        dimension: "Arbeitsverhalten",
        category: "Handlungsorientierung (HO)",
        umkehr: true,
    },
    {
        questionId: 92,
        dimension: "Soziale Kompetenzen",
        category: "Sensitivität (Sen)",
        umkehr: false,
    },
    {
        questionId: 93,
        dimension: "Soziale Kompetenzen",
        category: "Soziabilität (Soz)",
        umkehr: false,
    },
    {
        questionId: 94,
        dimension: "Soziale Kompetenzen",
        category: "Kontaktfähigkeit (Ko)",
        umkehr: false,
    },
    {
        questionId: 95,
        dimension: "Soziale Kompetenzen",
        category: "Teamorientierung (TO)",
        umkehr: false,
    },
    {
        questionId: 96,
        dimension: "Psychische Konstitution",
        category: "Emotionale Stabilität (Est)",
        umkehr: false,
    },
    {
        questionId: 97,
        dimension: "Psychische Konstitution",
        category: "Belastbarkeit (Bel)",
        umkehr: false,
    },
    {
        questionId: 98,
        dimension: "Psychische Konstitution",
        category: "Selbstbewusstsein (Sb)",
        umkehr: false,
    },
    {
        questionId: 99,
        dimension: "",
        category: "Kontrollerleben (Ke)",
        umkehr: true,
    },
    {
        questionId: 100,
        dimension: "Berufliche Orientierung",
        category: "Leistungsmotivation (LM)",
        umkehr: true,
    },
    {
        questionId: 101,
        dimension: "Berufliche Orientierung",
        category: "Gestaltungsmotivation (GM)",
        umkehr: true,
    },
    {
        questionId: 102,
        dimension: "Berufliche Orientierung",
        category: "Führungsmotivation (FM)",
        umkehr: false,
    },
    {
        questionId: 103,
        dimension: "Soziale Kompetenzen",
        category: "Durchsetzungsstärke (Du)",
        umkehr: false,
    },
    {
        questionId: 104,
        dimension: "Arbeitsverhalten",
        category: "Gewissenhaftigkeit (Ge)",
        umkehr: false,
    },
    {
        questionId: 105,
        dimension: "Arbeitsverhalten",
        category: "Flexibilität (FI)",
        umkehr: true,
    },
    {
        questionId: 106,
        dimension: "Arbeitsverhalten",
        category: "Handlungsorientierung (HO)",
        umkehr: false,
    },
    {
        questionId: 107,
        dimension: "Soziale Kompetenzen",
        category: "Sensitivität (Sen)",
        umkehr: true,
    },
    {
        questionId: 108,
        dimension: "Soziale Kompetenzen",
        category: "Soziabilität (Soz)",
        umkehr: false,
    },
    {
        questionId: 109,
        dimension: "Soziale Kompetenzen",
        category: "Kontaktfähigkeit (Ko)",
        umkehr: true,
    },
    {
        questionId: 110,
        dimension: "Soziale Kompetenzen",
        category: "Teamorientierung (TO)",
        umkehr: false,
    },
    {
        questionId: 111,
        dimension: "Psychische Konstitution",
        category: "Emotionale Stabilität (Est)",
        umkehr: false,
    },
    {
        questionId: 112,
        dimension: "Psychische Konstitution",
        category: "Belastbarkeit (Bel)",
        umkehr: true,
    },
    {
        questionId: 113,
        dimension: "Psychische Konstitution",
        category: "Selbstbewusstsein (Sb)",
        umkehr: false,
    },
    {
        questionId: 114,
        dimension: "",
        category: "Wettbewerbsorientierung (Wo)",
        umkehr: false,
    },
    {
        questionId: 115,
        dimension: "Berufliche Orientierung",
        category: "Leistungsmotivation (LM)",
        umkehr: true,
    },
    {
        questionId: 116,
        dimension: "Berufliche Orientierung",
        category: "Gestaltungsmotivation (GM)",
        umkehr: false,
    },
    {
        questionId: 117,
        dimension: "Berufliche Orientierung",
        category: "Führungsmotivation (FM)",
        umkehr: false,
    },
    {
        questionId: 118,
        dimension: "Soziale Kompetenzen",
        category: "Durchsetzungsstärke (Du)",
        umkehr: false,
    },
    {
        questionId: 119,
        dimension: "Arbeitsverhalten",
        category: "Gewissenhaftigkeit (Ge)",
        umkehr: true,
    },
    {
        questionId: 120,
        dimension: "Arbeitsverhalten",
        category: "Flexibilität (FI)",
        umkehr: false,
    },
    {
        questionId: 121,
        dimension: "Arbeitsverhalten",
        category: "Handlungsorientierung (HO)",
        umkehr: false,
    },
    {
        questionId: 122,
        dimension: "Soziale Kompetenzen",
        category: "Sensitivität (Sen)",
        umkehr: false,
    },
    {
        questionId: 123,
        dimension: "Soziale Kompetenzen",
        category: "Soziabilität (Soz)",
        umkehr: false,
    },
    {
        questionId: 124,
        dimension: "Soziale Kompetenzen",
        category: "Kontaktfähigkeit (Ko)",
        umkehr: false,
    },
    {
        questionId: 125,
        dimension: "Soziale Kompetenzen",
        category: "Teamorientierung (TO)",
        umkehr: true,
    },
    {
        questionId: 126,
        dimension: "Psychische Konstitution",
        category: "Emotionale Stabilität (Est)",
        umkehr: false,
    },
    {
        questionId: 127,
        dimension: "Psychische Konstitution",
        category: "Belastbarkeit (Bel)",
        umkehr: false,
    },
    {
        questionId: 128,
        dimension: "Psychische Konstitution",
        category: "Selbstbewusstsein (Sb)",
        umkehr: false,
    },
    {
        questionId: 129,
        dimension: "",
        category: "Kontrollerleben (Ke)",
        umkehr: false,
    },
    {
        questionId: 130,
        dimension: "Berufliche Orientierung",
        category: "Leistungsmotivation (LM)",
        umkehr: false,
    },
    {
        questionId: 131,
        dimension: "Berufliche Orientierung",
        category: "Gestaltungsmotivation (GM)",
        umkehr: true,
    },
    {
        questionId: 132,
        dimension: "Berufliche Orientierung",
        category: "Führungsmotivation (FM)",
        umkehr: true,
    },
    {
        questionId: 133,
        dimension: "Soziale Kompetenzen",
        category: "Durchsetzungsstärke (Du)",
        umkehr: true,
    },
    {
        questionId: 134,
        dimension: "Arbeitsverhalten",
        category: "Gewissenhaftigkeit (Ge)",
        umkehr: false,
    },
    {
        questionId: 135,
        dimension: "Arbeitsverhalten",
        category: "Flexibilität (FI)",
        umkehr: true,
    },
    {
        questionId: 136,
        dimension: "Arbeitsverhalten",
        category: "Handlungsorientierung (HO)",
        umkehr: false,
    },
    {
        questionId: 137,
        dimension: "Soziale Kompetenzen",
        category: "Soziabilität (Soz)",
        umkehr: false,
    },
    {
        questionId: 138,
        dimension: "Soziale Kompetenzen",
        category: "Kontaktfähigkeit (Ko)",
        umkehr: false,
    },
    {
        questionId: 139,
        dimension: "Soziale Kompetenzen",
        category: "Teamorientierung (TO)",
        umkehr: false,
    },
    {
        questionId: 140,
        dimension: "Psychische Konstitution",
        category: "Emotionale Stabilität (Est)",
        umkehr: true,
    },
    {
        questionId: 141,
        dimension: "Psychische Konstitution",
        category: "Belastbarkeit (Bel)",
        umkehr: false,
    },
    {
        questionId: 142,
        dimension: "Psychische Konstitution",
        category: "Selbstbewusstsein (Sb)",
        umkehr: false,
    },
    {
        questionId: 143,
        dimension: "",
        category: "Wettbewerbsorientierung (Wo)",
        umkehr: false,
    },
    {
        questionId: 144,
        dimension: "Berufliche Orientierung",
        category: "Leistungsmotivation (LM)",
        umkehr: false,
    },
    {
        questionId: 145,
        dimension: "Berufliche Orientierung",
        category: "Gestaltungsmotivation (GM)",
        umkehr: true,
    },
    {
        questionId: 146,
        dimension: "Berufliche Orientierung",
        category: "Führungsmotivation (FM)",
        umkehr: true,
    },
    {
        questionId: 147,
        dimension: "Soziale Kompetenzen",
        category: "Durchsetzungsstärke (Du)",
        umkehr: true,
    },
    {
        questionId: 148,
        dimension: "Arbeitsverhalten",
        category: "Gewissenhaftigkeit (Ge)",
        umkehr: true,
    },
    {
        questionId: 149,
        dimension: "Arbeitsverhalten",
        category: "Flexibilität (FI)",
        umkehr: false,
    },
    {
        questionId: 150,
        dimension: "Arbeitsverhalten",
        category: "Handlungsorientierung (HO)",
        umkehr: false,
    },
    {
        questionId: 151,
        dimension: "Soziale Kompetenzen",
        category: "Sensitivität (Sen)",
        umkehr: true,
    },
    {
        questionId: 152,
        dimension: "Soziale Kompetenzen",
        category: "Soziabilität (Soz)",
        umkehr: true,
    },
    {
        questionId: 153,
        dimension: "Soziale Kompetenzen",
        category: "Kontaktfähigkeit (Ko)",
        umkehr: true,
    },
    {
        questionId: 154,
        dimension: "Soziale Kompetenzen",
        category: "Teamorientierung (TO)",
        umkehr: true,
    },
    {
        questionId: 155,
        dimension: "Psychische Konstitution",
        category: "Emotionale Stabilität (Est)",
        umkehr: true,
    },
    {
        questionId: 156,
        dimension: "Psychische Konstitution",
        category: "Belastbarkeit (Bel)",
        umkehr: false,
    },
    {
        questionId: 157,
        dimension: "Psychische Konstitution",
        category: "Selbstbewusstsein (Sb)",
        umkehr: false,
    },
    {
        questionId: 158,
        dimension: "",
        category: "Kontrollerleben (Ke)",
        umkehr: false,
    },
    {
        questionId: 159,
        dimension: "Berufliche Orientierung",
        category: "Leistungsmotivation (LM)",
        umkehr: true,
    },
    {
        questionId: 160,
        dimension: "Berufliche Orientierung",
        category: "Führungsmotivation (FM)",
        umkehr: true,
    },
    {
        questionId: 161,
        dimension: "Soziale Kompetenzen",
        category: "Durchsetzungsstärke (Du)",
        umkehr: true,
    },
    {
        questionId: 162,
        dimension: "Arbeitsverhalten",
        category: "Gewissenhaftigkeit (Ge)",
        umkehr: true,
    },
    {
        questionId: 163,
        dimension: "Arbeitsverhalten",
        category: "Flexibilität (FI)",
        umkehr: true,
    },
    {
        questionId: 164,
        dimension: "Arbeitsverhalten",
        category: "Handlungsorientierung (HO)",
        umkehr: true,
    },
    {
        questionId: 165,
        dimension: "Soziale Kompetenzen",
        category: "Sensitivität (Sen)",
        umkehr: true,
    },
    {
        questionId: 166,
        dimension: "Soziale Kompetenzen",
        category: "Soziabilität (Soz)",
        umkehr: false,
    },
    {
        questionId: 167,
        dimension: "Soziale Kompetenzen",
        category: "Kontaktfähigkeit (Ko)",
        umkehr: true,
    },
    {
        questionId: 168,
        dimension: "Soziale Kompetenzen",
        category: "Teamorientierung (TO)",
        umkehr: false,
    },
    {
        questionId: 169,
        dimension: "Psychische Konstitution",
        category: "Emotionale Stabilität (Est)",
        umkehr: true,
    },
    {
        questionId: 170,
        dimension: "Psychische Konstitution",
        category: "Belastbarkeit (Bel)",
        umkehr: false,
    },
    {
        questionId: 171,
        dimension: "Psychische Konstitution",
        category: "Selbstbewusstsein (Sb)",
        umkehr: true,
    },
    {
        questionId: 172,
        dimension: "Berufliche Orientierung",
        category: "Leistungsmotivation (LM)",
        umkehr: true,
    },
    {
        questionId: 173,
        dimension: "Berufliche Orientierung",
        category: "Gestaltungsmotivation (GM)",
        umkehr: true,
    },
    {
        questionId: 174,
        dimension: "Berufliche Orientierung",
        category: "Führungsmotivation (FM)",
        umkehr: false,
    },
    {
        questionId: 175,
        dimension: "Soziale Kompetenzen",
        category: "Durchsetzungsstärke (Du)",
        umkehr: true,
    },
    {
        questionId: 176,
        dimension: "Arbeitsverhalten",
        category: "Gewissenhaftigkeit (Ge)",
        umkehr: true,
    },
    {
        questionId: 177,
        dimension: "Arbeitsverhalten",
        category: "Flexibilität (FI)",
        umkehr: false,
    },
    {
        questionId: 178,
        dimension: "Arbeitsverhalten",
        category: "Handlungsorientierung (HO)",
        umkehr: false,
    },
    {
        questionId: 179,
        dimension: "Soziale Kompetenzen",
        category: "Sensitivität (Sen)",
        umkehr: false,
    },
    {
        questionId: 180,
        dimension: "Soziale Kompetenzen",
        category: "Soziabilität (Soz)",
        umkehr: true,
    },
    {
        questionId: 181,
        dimension: "Soziale Kompetenzen",
        category: "Kontaktfähigkeit (Ko)",
        umkehr: true,
    },
    {
        questionId: 182,
        dimension: "Soziale Kompetenzen",
        category: "Teamorientierung (TO)",
        umkehr: true,
    },
    {
        questionId: 183,
        dimension: "Psychische Konstitution",
        category: "Emotionale Stabilität (Est)",
        umkehr: true,
    },
    {
        questionId: 184,
        dimension: "Psychische Konstitution",
        category: "Belastbarkeit (Bel)",
        umkehr: false,
    },
    {
        questionId: 185,
        dimension: "Psychische Konstitution",
        category: "Selbstbewusstsein (Sb)",
        umkehr: true,
    },
    {
        questionId: 186,
        dimension: "Berufliche Orientierung",
        category: "Gestaltungsmotivation (GM)",
        umkehr: true,
    },
    {
        questionId: 187,
        dimension: "Berufliche Orientierung",
        category: "Führungsmotivation (FM)",
        umkehr: false,
    },
    {
        questionId: 188,
        dimension: "Arbeitsverhalten",
        category: "Gewissenhaftigkeit (Ge)",
        umkehr: true,
    },
    {
        questionId: 189,
        dimension: "Arbeitsverhalten",
        category: "Flexibilität (FI)",
        umkehr: false,
    },
    {
        questionId: 190,
        dimension: "Arbeitsverhalten",
        category: "Handlungsorientierung (HO)",
        umkehr: false,
    },
    {
        questionId: 191,
        dimension: "Soziale Kompetenzen",
        category: "Sensitivität (Sen)",
        umkehr: false,
    },
    {
        questionId: 192,
        dimension: "Soziale Kompetenzen",
        category: "Kontaktfähigkeit (Ko)",
        umkehr: true,
    },
    {
        questionId: 193,
        dimension: "Psychische Konstitution",
        category: "Emotionale Stabilität (Est)",
        umkehr: false,
    },
    {
        questionId: 194,
        dimension: "Psychische Konstitution",
        category: "Selbstbewusstsein (Sb)",
        umkehr: true,
    },
    {
        questionId: 195,
        dimension: "",
        category: "Wettbewerbsorientierung (Wo)",
        umkehr: true,
    },
    {
        questionId: 196,
        dimension: "Berufliche Orientierung",
        category: "Leistungsmotivation (LM)",
        umkehr: false,
    },
    {
        questionId: 197,
        dimension: "Berufliche Orientierung",
        category: "Führungsmotivation (FM)",
        umkehr: true,
    },
    {
        questionId: 198,
        dimension: "Arbeitsverhalten",
        category: "Flexibilität (FI)",
        umkehr: true,
    },
    {
        questionId: 199,
        dimension: "Arbeitsverhalten",
        category: "Handlungsorientierung (HO)",
        umkehr: true,
    },
    {
        questionId: 200,
        dimension: "Soziale Kompetenzen",
        category: "Soziabilität (Soz)",
        umkehr: true,
    },
    {
        questionId: 201,
        dimension: "Soziale Kompetenzen",
        category: "Kontaktfähigkeit (Ko)",
        umkehr: true,
    },
    {
        questionId: 202,
        dimension: "Psychische Konstitution",
        category: "Emotionale Stabilität (Est)",
        umkehr: true,
    },
    {
        questionId: 203,
        dimension: "Psychische Konstitution",
        category: "Selbstbewusstsein (Sb)",
        umkehr: false,
    },
    {
        questionId: 204,
        dimension: "Berufliche Orientierung",
        category: "Leistungsmotivation (LM)",
        umkehr: true,
    },
    {
        questionId: 205,
        dimension: "Berufliche Orientierung",
        category: "Führungsmotivation (FM)",
        umkehr: false,
    },
    {
        questionId: 206,
        dimension: "Arbeitsverhalten",
        category: "Gewissenhaftigkeit (Ge)",
        umkehr: true,
    },
    {
        questionId: 207,
        dimension: "Soziale Kompetenzen",
        category: "Soziabilität (Soz)",
        umkehr: false,
    },
    {
        questionId: 208,
        dimension: "Soziale Kompetenzen",
        category: "Kontaktfähigkeit (Ko)",
        umkehr: true,
    },
    {
        questionId: 209,
        dimension: "Psychische Konstitution",
        category: "Emotionale Stabilität (Est)",
        umkehr: true,
    },
    {
        questionId: 210,
        dimension: "Psychische Konstitution",
        category: "Selbstbewusstsein (Sb)",
        umkehr: true,
    },
];

const SCORING = {
    "Leistungsmotivation (LM)": {
        1: [14, 35],
        2: [36, 42],
        3: [43, 48],
        4: [49, 54],
        5: [55, 59],
        6: [60, 64],
        7: [65, 69],
        8: [70, 73],
        9: [74, 77],
        10: [78, 84],
    },
    "Gestaltungsmotivation (GM)": {
        1: [12, 30],
        2: [31, 35],
        3: [36, 39],
        4: [40, 44],
        5: [45, 48],
        6: [49, 52],
        7: [53, 56],
        8: [57, 60],
        9: [61, 63],
        10: [64, 72],
    },
    "Führungsmotivation (FM)": {
        1: [15, 32],
        2: [33, 39],
        3: [40, 47],
        4: [48, 55],
        5: [56, 62],
        6: [63, 68],
        7: [69, 73],
        8: [74, 78],
        9: [79, 82],
        10: [83, 90],
    },
    "Gewissenhaftigkeit (Ge)": {
        1: [14, 30],
        2: [31, 36],
        3: [37, 42],
        4: [43, 48],
        5: [49, 54],
        6: [55, 60],
        7: [61, 66],
        8: [67, 71],
        9: [72, 75],
        10: [76, 84],
    },
    "Flexibilität (FI)": {
        1: [14, 32],
        2: [33, 39],
        3: [40, 46],
        4: [47, 53],
        5: [54, 59],
        6: [60, 65],
        7: [66, 70],
        8: [71, 75],
        9: [76, 79],
        10: [80, 84],
    },
    "Handlungsorientierung (HO)": {
        1: [14, 30],
        2: [31, 37],
        3: [38, 44],
        4: [45, 52],
        5: [53, 59],
        6: [60, 64],
        7: [65, 70],
        8: [71, 74],
        9: [75, 78],
        10: [79, 84],
    },
    "Sensitivität (Sen)": {
        1: [12, 31],
        2: [32, 36],
        3: [37, 42],
        4: [43, 48],
        5: [49, 53],
        6: [54, 57],
        7: [58, 61],
        8: [62, 64],
        9: [65, 68],
        10: [69, 72],
    },
    "Kontaktfähigkeit (Ko)": {
        1: [16, 33],
        2: [34, 40],
        3: [41, 49],
        4: [50, 58],
        5: [59, 66],
        6: [67, 73],
        7: [74, 80],
        8: [81, 85],
        9: [86, 89],
        10: [90, 96],
    },
    "Soziabilität (Soz)": {
        1: [15, 37],
        2: [38, 42],
        3: [43, 47],
        4: [48, 52],
        5: [53, 57],
        6: [58, 62],
        7: [63, 67],
        8: [68, 72],
        9: [73, 76],
        10: [77, 90],
    },
    "Teamorientierung (TO)": {
        1: [13, 24],
        2: [25, 30],
        3: [31, 38],
        4: [39, 44],
        5: [45, 51],
        6: [52, 57],
        7: [58, 63],
        8: [64, 68],
        9: [69, 72],
        10: [73, 78],
    },
    "Durchsetzungsstärke (Du)": {
        1: [12, 27],
        2: [28, 33],
        3: [34, 39],
        4: [40, 44],
        5: [45, 49],
        6: [50, 53],
        7: [54, 57],
        8: [58, 61],
        9: [62, 64],
        10: [65, 72],
    },
    "Emotionale Stabilität (Est)": {
        1: [16, 26],
        2: [27, 34],
        3: [35, 41],
        4: [42, 49],
        5: [50, 57],
        6: [58, 64],
        7: [65, 71],
        8: [72, 77],
        9: [78, 83],
        10: [84, 96],
    },
    "Belastbarkeit (Bel)": {
        1: [13, 27],
        2: [28, 34],
        3: [35, 41],
        4: [42, 49],
        5: [50, 55],
        6: [56, 62],
        7: [63, 67],
        8: [68, 72],
        9: [73, 75],
        10: [76, 78],
    },
    "Selbstbewusstsein (Sb)": {
        1: [16, 33],
        2: [34, 40],
        3: [41, 47],
        4: [48, 54],
        5: [55, 61],
        6: [62, 67],
        7: [68, 72],
        8: [73, 78],
        9: [79, 83],
        10: [84, 96],
    },
};

export { DIMENSIONS, CATEGORIES, questions, SCORING };
